# Offense count: 3
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
    - '**/spec/routing/**/*'
    - '**/spec/system/**/*'
    - '**/spec/views/**/*'
    - 'spec/acceptance/init_spec.rb'
    - 'spec/acceptance/linux_spec.rb'
    - 'spec/acceptance/windows_spec.rb'

# Offense count: 11
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 12

# Offense count: 16
RSpec/MultipleExpectations:
  Max: 5

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowedVars.
# Style/FetchEnvVar:
#   Exclude:
#     - 'spec/acceptance/linux_spec.rb'
#     - 'spec/acceptance/windows_spec.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/GlobalStdStream:
  Exclude:
    - 'tasks/init.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Style/NegatedIfElseCondition:
  Exclude:
    - 'spec/acceptance/init_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'spec/spec_helper.rb'
